services:
  - type: web
    name: consultigo-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: consultigo-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://consultigo-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60

  - type: web
    name: consultigo-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: starter
    envVars:
      - key: BACKEND_URL
        value: https://consultigo-backend.onrender.com

databases:
  - name: consultigo-db
    databaseName: consultigo
    plan: starter 